name: better_dart_ip
version: 0.1.1
homepage: https://github.com/mohn93/dart_ip
description: A package for working with the IP protocol stack (IPv4, IPv6, ICMP, TCP, UDP).

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: '^1.0.0'
  dart_raw: ^0.2.0

dev_dependencies:
  pedantic: '^1.0.0'
  test: '^1.4.0'